### ISSUE TITLE
No module named 'google' Error

### ISSUE THREAD

**Issue by raymond30031** [jmccormac/pySceneNetRGBD#12]
Hello,

After I make, i have the scenenet_pb2 module, but when i try to run the read_protobuf.py i get:

jkuo@jkuo-pc:~/plr/pySceneNetRGBD$ python read_protobuf.py
Traceback (most recent call last):
File "read_protobuf.py", line 1, in 
import scenenet_pb2 as sn
File "/home/jkuo/plr/pySceneNetRGBD/scenenet_pb2.py", line 6, in 
from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

I am currently googling on how to solve this, but would just like to ask here in case anyone has any inputs.

Thanks.

**Comment by jmccormac** [comment]
This looks like protobuf has not been installed.  If you have installed it with pip3 as in the readme, then maybe the issue is that you are running with python2 by default when running ```python``` which hasn't had protobuf installed?  Have you tried running with:

```
python3 read_protobuf.py
```

**Comment by jmccormac** [comment]
Thank you very much for reporting the solution! It may help someone else as well.
